flowchart LR
    C([Client])
    G([Gérant])
    C --- U1((Demander<br/>un devis))
    C --- U2((Prendre<br/>rendez-vous))
    C --- U3((Question<br/>technique))
    C --- U4((SAV /<br/>garantie))
    G --- U5((Recevoir une<br/>notification))
